-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 13:37:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Schema ELearningPlatform
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ELearningPlatform` DEFAULT CHARACTER SET utf8 ;
USE `ELearningPlatform` ;

-- -----------------------------------------------------
-- Table `ELearningPlatform`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`ROLES` (
  `Code` INT NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`USERS` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`USERS` (
  `Nickname` VARCHAR(45) NOT NULL,
  `RoleCode` INT NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `IsConfirmed` TINYINT(1) NULL,
  `Password` VARCHAR(50) NULL,
  PRIMARY KEY (`Nickname`),
  INDEX `fk_USERS_ROLES1_idx` (`RoleCode` ASC),
  CONSTRAINT `fk_USERS_ROLES1`
    FOREIGN KEY (`RoleCode`)
    REFERENCES `ELearningPlatform`.`ROLES` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`TOKENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`TOKENS` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`TOKENS` (
  `ValidateTill` DATETIME NOT NULL,
  `Nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nickname`),
  CONSTRAINT `fk_TOKENS_USERS`
    FOREIGN KEY (`Nickname`)
    REFERENCES `ELearningPlatform`.`USERS` (`Nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`COURSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`COURSES` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`COURSES` (
  `idCourse` INT NOT NULL AUTO_INCREMENT,
  `TeacherNickname` VARCHAR(45) NOT NULL,
  `Label` VARCHAR(45) NULL,
  `IsEnable` TINYINT NULL,
  PRIMARY KEY (`idCourse`),
  INDEX `fk_COURSES_USERS1_idx` (`TeacherNickname` ASC),
  CONSTRAINT `fk_COURSES_USERS1`
    FOREIGN KEY (`TeacherNickname`)
    REFERENCES `ELearningPlatform`.`USERS` (`Nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`PARTICIPATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`PARTICIPATIONS` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`PARTICIPATIONS` (
  `Nickname` VARCHAR(45) NOT NULL,
  `idCourse` INT NOT NULL,
  PRIMARY KEY (`Nickname`, `idCourse`),
  INDEX `fk_PARTICIPATIONS_COURSES1_idx` (`idCourse` ASC),
  CONSTRAINT `fk_PARTICIPATIONS_USERS1`
    FOREIGN KEY (`Nickname`)
    REFERENCES `ELearningPlatform`.`USERS` (`Nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTICIPATIONS_COURSES1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `ELearningPlatform`.`COURSES` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`PAGESCOURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`PAGESCOURSE` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`PAGESCOURSE` (
  `idPageCourse` INT NOT NULL AUTO_INCREMENT,
  `Desc` LONGTEXT NULL,
  `idCourse` INT NOT NULL,
  `DateCreation` DATETIME NOT NULL,
  PRIMARY KEY (`idPageCourse`),
  INDEX `fk_PAGESCOURSE_COURSES1_idx` (`idCourse` ASC),
  CONSTRAINT `fk_PAGESCOURSE_COURSES1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `ELearningPlatform`.`COURSES` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ELearningPlatform`.`COMPLETEDCOURSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ELearningPlatform`.`COMPLETEDCOURSES` ;

CREATE TABLE IF NOT EXISTS `ELearningPlatform`.`COMPLETEDCOURSES` (
  `Nickname` VARCHAR(45) NOT NULL,
  `idCourse` INT NOT NULL,
  `idPageCourse` INT NOT NULL,
  `IsCompleted` TINYINT NOT NULL,
  PRIMARY KEY (`Nickname`, `idCourse`, `idPageCourse`),
  INDEX `fk_COMPLETEDCOURSES_PAGESCOURSE1_idx` (`idPageCourse` ASC),
  CONSTRAINT `fk_COMPLETEDCOURSES_PARTICIPATIONS1`
    FOREIGN KEY (`Nickname` , `idCourse`)
    REFERENCES `ELearningPlatform`.`PARTICIPATIONS` (`Nickname` , `idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPLETEDCOURSES_PAGESCOURSE1`
    FOREIGN KEY (`idPageCourse`)
    REFERENCES `ELearningPlatform`.`PAGESCOURSE` (`idPageCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
